app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

controllers:
    resource: ../src/Controller/
    type: attribute

index:
    path: /
    controller: App\Controller\SortieController::home